// =============================================
// CURRENCIES
// =============================================
export const currencies = [
  { code: "USD", label: "United States (USD $)", symbol: "$" },
  { code: "AUD", label: "Australia (AUD $)", symbol: "$" },
  { code: "EUR", label: "Austria (EUR €)", symbol: "€" },
  { code: "EUR", label: "Belgium (EUR €)", symbol: "€" },
  { code: "CAD", label: "Canada (CAD $)", symbol: "$" },
  { code: "CNY", label: "China (CNY ¥)", symbol: "¥" },
  { code: "CZK", label: "Czechia (CZK Kč)", symbol: "Kč" },
  { code: "DKK", label: "Denmark (DKK kr.)", symbol: "kr." },
  { code: "EUR", label: "France (EUR €)", symbol: "€" },
  { code: "EUR", label: "Germany (EUR €)", symbol: "€" },
  { code: "EUR", label: "Greece (EUR €)", symbol: "€" },
  { code: "HKD", label: "Hong Kong SAR (HKD $)", symbol: "$" },
  { code: "HUF", label: "Hungary (HUF Ft)", symbol: "Ft" },
  { code: "INR", label: "India (INR ₹)", symbol: "₹" },
  { code: "IDR", label: "Indonesia (IDR Rp)", symbol: "Rp" },
  { code: "ILS", label: "Israel (ILS ₪)", symbol: "₪" },
  { code: "EUR", label: "Italy (EUR €)", symbol: "€" },
  { code: "EUR", label: "Luxembourg (EUR €)", symbol: "€" },
  { code: "MOP", label: "Macao SAR (MOP P)", symbol: "P" },
  { code: "MYR", label: "Malaysia (MYR RM)", symbol: "RM" },
  { code: "MXN", label: "Mexico (MXN $)", symbol: "$" },
  { code: "EUR", label: "Monaco (EUR €)", symbol: "€" },
  { code: "EUR", label: "Montenegro (EUR €)", symbol: "€" },
  { code: "NPR", label: "Nepal (NPR Rs.)", symbol: "Rs." },
  { code: "EUR", label: "Netherlands (EUR €)", symbol: "€" },
  { code: "NZD", label: "New Zealand (NZD $)", symbol: "$" },
  { code: "NOK", label: "Norway (NOK kr)", symbol: "kr" },
  { code: "PHP", label: "Philippines (PHP ₱)", symbol: "₱" },
  { code: "PLN", label: "Poland (PLN zł)", symbol: "zł" },
  { code: "EUR", label: "Portugal (EUR €)", symbol: "€" },
  { code: "QAR", label: "Qatar (QAR ر.ق)", symbol: "ر.ق" },
  { code: "SGD", label: "Singapore (SGD $)", symbol: "$" },
  { code: "KRW", label: "South Korea (KRW ₩)", symbol: "₩" },
  { code: "EUR", label: "Spain (EUR €)", symbol: "€" },
  { code: "SEK", label: "Sweden (SEK kr)", symbol: "kr" },
  { code: "CHF", label: "Switzerland (CHF CHF)", symbol: "CHF" },
  { code: "TWD", label: "Taiwan (TWD $)", symbol: "$" },
  { code: "THB", label: "Thailand (THB ฿)", symbol: "฿" },
  { code: "AED", label: "United Arab Emirates (AED د.إ)", symbol: "د.إ" },
  { code: "GBP", label: "United Kingdom (GBP £)", symbol: "£" },
  { code: "VND", label: "Vietnam (VND ₫)", symbol: "₫" },
];

// =============================================
// CATEGORIES
// =============================================
export const categories = [
  { id: "pokemon", name: "Pokémon Cards", slug: "pokemon", emoji: "⚡" },
  { id: "onepiece", name: "One Piece Cards", slug: "one-piece", emoji: "⚓" },
  { id: "lorcana", name: "Disney LORCANA", slug: "disney-lorcana", emoji: "✨" },
  { id: "dragonball", name: "Dragon Ball Cards", slug: "dragon-ball", emoji: "🐉" },
  { id: "grading", name: "Grading Cards", slug: "grading", emoji: "🏆" },
];

// =============================================
// PRODUCTS — One Piece Booster Boxes (OP-01 to OP-17)
// =============================================
export const onePieceBoosterBoxes = [
  {
    id: "tcg-op-17",
    name: "【OP-17】The World's Strongest Warriors TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-17-worlds-strongest-warriors-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 232.02,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/2026-04-22133052.png?v=1776832268",
    badge: "new",
    reviews: 0,
    brand: "TCG SHOP KASUMI",
    description: "The latest One Piece TCG set featuring the World's Strongest Warriors with powerful new cards. Factory sealed for guaranteed authenticity.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-16",
    name: "【OP-16】The Time Of Battle TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-16-time-of-battle-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 116.15,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/m65276232534_1.jpg?v=1783189129",
    badge: "hot",
    reviews: 5,
    brand: "TCG SHOP KASUMI",
    description: "The Time of Battle features epic clashes and iconic moments from the One Piece anime.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-15",
    name: "【OP-15】Adventure on the Island of the Gods TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-15-adventure-island-gods-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 119.77,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/51XbrLjTUtL._AC_SL1500.jpg?v=1782111775",
    badge: null,
    reviews: 3,
    brand: "TCG SHOP KASUMI",
    description: "Adventure on the Island of the Gods brings the Egghead arc to life with stunning cards.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-eb-04",
    name: "【EB-04】Extra Booster EGGHEAD CRISIS TCG BOX & CASE〔Factory Sealed〕",
    slug: "eb-04-extra-booster-egghead-crisis-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 103.84,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/CRPCLK-025.jpg?v=1712749019",
    badge: null,
    reviews: 2,
    brand: "TCG SHOP KASUMI",
    description: "Extra Booster set themed around the Egghead Crisis arc with exclusive cards.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-14",
    name: "【OP-14】The Azure Sea's Seven TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-14-azure-seas-seven-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 119.77,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/2026-04-22133052.png?v=1776832268",
    badge: null,
    reviews: 4,
    brand: "TCG SHOP KASUMI",
    description: "Features the Shichibukai — Seven Warlords of the Sea with powerful leader cards.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-13",
    name: "【OP-13】Ultra Deck: The Three Captains TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-13-ultra-deck-three-captains-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 109.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/m65276232534_1.jpg?v=1783189129",
    badge: null,
    reviews: 6,
    brand: "TCG SHOP KASUMI",
    description: "Ultra Deck featuring The Three Captains with premium cards and exclusive artwork.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-12",
    name: "【OP-12】Side Story of Vivi TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-12-side-story-of-vivi-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 94.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/51XbrLjTUtL._AC_SL1500.jpg?v=1782111775",
    badge: null,
    reviews: 8,
    brand: "TCG SHOP KASUMI",
    description: "Side story set focusing on Vivi's journey with unique character cards.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-11",
    name: "【OP-11】A Fist of Divine Speed TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-11-fist-divine-speed-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 104.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/CRPCLK-025.jpg?v=1712749019",
    badge: null,
    reviews: 7,
    brand: "TCG SHOP KASUMI",
    description: "A Fist of Divine Speed brings lightning-fast combat to the One Piece TCG.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-10",
    name: "【OP-10】Royal Knight TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-10-royal-knight-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 104.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/2026-04-22133052.png?v=1776832268",
    badge: null,
    reviews: 9,
    brand: "TCG SHOP KASUMI",
    description: "Royal Knight features the noble warriors of the One Piece world.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-09",
    name: "【OP-09】Emperors in the New World TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-09-emperors-new-world-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 99.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/m65276232534_1.jpg?v=1783189129",
    badge: null,
    reviews: 11,
    brand: "TCG SHOP KASUMI",
    description: "Emperors in the New World showcases the most powerful rulers of the seas.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-08",
    name: "【OP-08】Two Legends TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-08-two-legends-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 94.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/51XbrLjTUtL._AC_SL1500.jpg?v=1782111775",
    badge: null,
    reviews: 14,
    brand: "TCG SHOP KASUMI",
    description: "Two Legends brings the iconic duels of One Piece's greatest heroes together.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-07",
    name: "【OP-07】500 Years in the Future TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-07-500-years-future-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 89.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/CRPCLK-025.jpg?v=1712749019",
    badge: null,
    reviews: 16,
    brand: "TCG SHOP KASUMI",
    description: "500 Years in the Future explores the ancient mysteries of the One Piece world.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-06",
    name: "【OP-06】Wings of the Captain TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-06-wings-of-captain-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 84.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/2026-04-22133052.png?v=1776832268",
    badge: null,
    reviews: 19,
    brand: "TCG SHOP KASUMI",
    description: "Wings of the Captain features the trusted crew members of the Straw Hat Pirates.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-05",
    name: "【OP-05】Awakening of the New Era TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-05-awakening-new-era-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 79.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/m65276232534_1.jpg?v=1783189129",
    badge: null,
    reviews: 23,
    brand: "TCG SHOP KASUMI",
    description: "Awakening of the New Era marks a turning point in the One Piece TCG journey.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-04",
    name: "【OP-04】Kingdoms of Intrigue TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-04-kingdoms-of-intrigue-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 79.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/51XbrLjTUtL._AC_SL1500.jpg?v=1782111775",
    badge: null,
    reviews: 28,
    brand: "TCG SHOP KASUMI",
    description: "Kingdoms of Intrigue brings political drama and powerful nation leaders to your deck.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-03",
    name: "【OP-03】Pillars of Strength TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-03-pillars-of-strength-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 74.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/CRPCLK-025.jpg?v=1712749019",
    badge: null,
    reviews: 31,
    brand: "TCG SHOP KASUMI",
    description: "Pillars of Strength features the most powerful fighters from across the One Piece world.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-02",
    name: "【OP-02】Paramount War TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-02-paramount-war-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 69.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/2026-04-22133052.png?v=1776832268",
    badge: null,
    reviews: 38,
    brand: "TCG SHOP KASUMI",
    description: "Paramount War recreates the legendary Marineford war with iconic cards.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg-op-01",
    name: "【OP-01】Romance Dawn TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-01-romance-dawn-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 64.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/m65276232534_1.jpg?v=1783189129",
    badge: null,
    reviews: 52,
    brand: "TCG SHOP KASUMI",
    description: "Romance Dawn is where the One Piece TCG journey begins — the original first set.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
];

// =============================================
// PRODUCTS — Pokémon Booster Boxes
// =============================================
export const pokemonBoosterBoxes = [
  {
    id: "tcg-m6",
    name: "【M6】Storm Emeralda TCG BOX & CASE〔Factory Sealed〕",
    slug: "m6-storm-emeralda-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 223.75,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/715FaccxhwL._AC_SL1500.jpg?v=1781851810",
    badge: "new",
    reviews: 0,
    brand: "TCG SHOP KASUMI",
    description: "The latest Mega TCG set, Storm Emeralda, featuring powerful new cards and stunning artwork. Factory sealed for guaranteed authenticity.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
  {
    id: "tcg-m6a",
    name: "【M6a】30th CELEBRATION TCG BOX & CASE〔Factory Sealed〕",
    slug: "m6a-30th-celebration-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 293.38,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/711dPI8FndL._AC_SX679.jpg?v=1780628525",
    badge: "hot",
    reviews: 0,
    brand: "TCG SHOP KASUMI",
    description: "Celebrate 30 years of Pokémon with this special anniversary set. Includes exclusive celebration cards.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
  {
    id: "tcg-m5",
    name: "【M5】Abyss Eye Booster TCG BOX & CASE〔Factory Sealed〕",
    slug: "m5-abyss-eye-booster-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 86.02,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/IMG_5898.jpg?v=1779670111",
    badge: null,
    reviews: 13,
    brand: "TCG SHOP KASUMI",
    description: "Dive into the depths with the Abyss Eye set. Features Darkrai EX and other powerful deep-sea Pokémon.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
  {
    id: "tcg-m4",
    name: "【M4】Ninja Spinner Booster TCG BOX & CASE〔Factory Sealed〕",
    slug: "m4-ninja-spinner-booster-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 88.22,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/IMG_4507.jpg?v=1773623226",
    badge: null,
    reviews: 5,
    brand: "TCG SHOP KASUMI",
    description: "Fast and fierce ninja-themed set with powerful Fighting and Dark type cards.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
  {
    id: "tcg-m3",
    name: "【M3】Munikis Zero Booster TCG BOX & CASE〔Factory Sealed〕",
    slug: "m3-munikis-zero-booster-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 69.90,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/IMG_3336.jpg?v=1769388977",
    badge: null,
    reviews: 3,
    brand: "TCG SHOP KASUMI",
    description: "Munikis Zero brings a new level of strategy to the Mega TCG with innovative card mechanics.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
  {
    id: "tcg-m2a",
    name: "【M2a】Terastal Festival TCG BOX & CASE〔Factory Sealed〕",
    slug: "m2a-terastal-festival-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 74.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/IMG_5898.jpg",
    badge: null,
    reviews: 15,
    brand: "TCG SHOP KASUMI",
    description: "Terastal Festival features the most beloved Pokémon in their Terastal forms.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
  {
    id: "tcg-svh",
    name: "【SVH】Pokémon 151 Scarlet & Violet TCG BOX & CASE〔Factory Sealed〕",
    slug: "svh-pokemon-151-scarlet-violet-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 129.99,
    image: "https://cdn.shopify.com/s/files/1/0614/1499/8212/files/IMG_4502.jpg",
    badge: null,
    reviews: 22,
    brand: "TCG SHOP KASUMI",
    description: "Scarlet & Violet set featuring all 151 original Pokémon in stunning new art.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
];

// =============================================
// PRODUCTS — Pokémon Single Cards
// =============================================
export const singleCards = [
  {
    id: 'm5-mega-chandelure',
    name: '[M5] Mega Chandelure ex 036/081〈RR〉',
    slug: 'm5-mega-chandelure-ex-036-081-rr',
    category: 'pokemon',
    subcategory: 'single',
    price: 1.01,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/xmF1v39ZqNhWwG78VOKaL62V8o4oBARG8EZOK4C2_500x_9d3b8e93-806a-41e6-bbda-c3d990cd7029.jpg?v=1779782821',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic Pokemon TCG single card.'
  },
  {
    id: 'm5-brave-bangle',
    name: '[M5] Brave Bangle 107/081〈SR〉',
    slug: 'm5-brave-bangle-107-081-sr',
    category: 'pokemon',
    subcategory: 'single',
    price: 2.73,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/8qxJEiQHFgKxKu6TIDjJQeycldDoXotLto3tZaKm_500x_6c207761-8166-4270-9951-d4efa267aaa3.jpg?v=1779782818',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic Pokemon TCG single card.'
  },
  {
    id: 'm5-crushing-hammer',
    name: '[M5] Crushing Hammer 104/081〈SR〉',
    slug: 'm5-crushing-hammer-104-081-sr',
    category: 'pokemon',
    subcategory: 'single',
    price: 2.73,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/BLS95iZS6gUZiGeQLVhEi1I5BNDmMsNXD2RtRydw_500x_beb3b1cf-68bf-401f-b641-55c8c9de5e44.jpg?v=1779782816',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic Pokemon TCG single card.'
  },
  {
    id: 'm5-zarude',
    name: '[M5] Zarude 090/081〈AR〉',
    slug: 'm5-zarude-090-081-ar',
    category: 'pokemon',
    subcategory: 'single',
    price: 3.93,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/2aYL1PI4ZzibAFAx66tbTtU3QsQTcJqtLKJVoaXz_500x_faf9a9de-8749-4d56-b849-40bd244933ca.jpg?v=1779782811',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic Pokemon TCG single card.'
  },
  {
    id: 'm5-manectric',
    name: '[M5] Manectric 086/081〈AR〉',
    slug: 'm5-manectric-086-081-ar',
    category: 'pokemon',
    subcategory: 'single',
    price: 3.93,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/NsD3IZ0eQdNH8KyLeeGCj0KqKqMl2uc42373iSB6_500x_b219e128-1152-4f62-940c-b65a7de73448.jpg?v=1779782808',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic Pokemon TCG single card.'
  },
  {
    id: 'm5-armarouge',
    name: '[M5] Armarouge 083/081〈AR〉',
    slug: 'm5-armarouge-083-081-ar',
    category: 'pokemon',
    subcategory: 'single',
    price: 3.98,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/DsmvjeLMNZG6U6F6Ikakk7odWGk3THHH63vkZxec_500x_24121bbf-5788-478e-a4ec-28d74ec98f75.jpg?v=1779782805',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic Pokemon TCG single card.'
  },
  {
    id: 'm5-fomantis',
    name: '[M5] Fomantis 082/081〈AR〉',
    slug: 'm5-fomantis-082-081-ar',
    category: 'pokemon',
    subcategory: 'single',
    price: 3.98,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/IGwDv2ky3HyPtBCi8ULIChCNj6GolfYmwgxUi2Zd_500x_7d4cff45-184f-4ede-bf64-ee13c2d751d7.jpg?v=1779782802',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic Pokemon TCG single card.'
  },
  {
    id: 'op-p-159-monkey-d-luffy',
    name: '[P-159] Monkey.D.Luffy P',
    slug: 'op-p-159-monkey-d-luffy',
    category: 'onepiece',
    subcategory: 'single',
    price: 34.35,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/p-159.webp?v=1783531311',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic One Piece TCG single card.'
  },
  {
    id: 'op-p-041-monkey-d-luffy',
    name: '[P-041] Monkey.D.Luffy P〈ONE PIECE EMOTION〉',
    slug: 'op-p-041-monkey-d-luffy',
    category: 'onepiece',
    subcategory: 'single',
    price: 63.41,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/m65276232534_1.jpg?v=1783189129',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic One Piece TCG single card.'
  },
  {
    id: 'op-monkey-d-luffy-watermelon',
    name: 'Monkey.D.Luffy Watermelon〈NatsuComi Summer Comics Fair 2026〉',
    slug: 'op-monkey-d-luffy-watermelon',
    category: 'onepiece',
    subcategory: 'single',
    price: 42.85,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/2026_1.png?v=1782539202',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic One Piece TCG single card.'
  },
  {
    id: 'op16-055-mr-2',
    name: '[OP16-055] Mr.2.Bon.Kurei(Bentham) R/P〈Parallel〉',
    slug: 'op16-055-mr-2-bon-kurei-bentham',
    category: 'onepiece',
    subcategory: 'single',
    price: 28.47,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/OP16_P_0528_13.jpg?v=1780165338',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic One Piece TCG single card.'
  },
  {
    id: 'op16-082-kinemon',
    name: '[OP16-082] Kinemon SR/P〈Parallel〉',
    slug: 'op16-082-kinemon',
    category: 'onepiece',
    subcategory: 'single',
    price: 31.29,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/OP16_P_0528_21.jpg?v=1780165332',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic One Piece TCG single card.'
  },
  {
    id: 'op16-014-marco',
    name: '[OP16-014] Marco R/P〈Parallel〉',
    slug: 'op16-014-marco',
    category: 'onepiece',
    subcategory: 'single',
    price: 27.65,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/OP16_P_0528_3.jpg?v=1780165326',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic One Piece TCG single card.'
  },
  {
    id: 'op16-085-kozuki-momonosuke',
    name: '[OP16-085] Kozuki Momonosuke R/P〈Parallel〉',
    slug: 'op16-085-kozuki-momonosuke',
    category: 'onepiece',
    subcategory: 'single',
    price: 33.03,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/OP16_P_0528_22.jpg?v=1780165318',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    variants: ['Near Mint (NM)', 'Excellent (EX)'],
    description: 'Authentic One Piece TCG single card.'
  }
];

// =============================================
// PRODUCTS — Deck Sets
// =============================================
export const deckSets = [
  {
    id: '30th-celebration-futuristic-box',
    name: '30th CELEBRATION FUTURISTIC BOX',
    slug: '30th-celebration-futuristic-box',
    category: 'pokemon',
    subcategory: 'deck',
    price: 1000.00,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/5_89fad6ab-c531-4f9a-99ae-c6ed9cf29f68.png?v=1783486530',
    badge: 'hot',
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    description: 'Authentic TCG deck set.',
    variants: null,
  },
  {
    id: '30th-celebration-premium-tcg-deck-set-espeon-umbreon',
    name: '30th CELEBRATION Premium TCG Deck set Espeon・Umbreon',
    slug: '30th-celebration-premium-tcg-deck-set-espeon-umbreon',
    category: 'pokemon',
    subcategory: 'deck',
    price: 499.99,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/71RQY_K9JzL._AC_SL1500.jpg?v=1783407574',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    description: 'Authentic TCG deck set.',
    variants: null,
  },
  {
    id: 'mega-starter-set-ex-eevee-ex',
    name: 'MEGA Starter Set ex (Eevee ex)',
    slug: 'mega-starter-set-ex-eevee-ex',
    category: 'pokemon',
    subcategory: 'deck',
    price: 80.00,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/deck_pkg-ylw-m0te1g6j.png?v=1783405531',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    description: 'Authentic TCG deck set.',
    variants: null,
  },
  {
    id: 'mega-starter-set-ex-zorua-zoroark-ex',
    name: 'MEGA Starter Set ex (Zorua & Zoroark ex)',
    slug: 'mega-starter-set-ex-zorua-zoroark-ex',
    category: 'pokemon',
    subcategory: 'deck',
    price: 80.00,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/deck_pkg-blu-ky1bq7p1_e819b0a5-197e-460b-b675-5696985bff8c.png?v=1783405548',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    description: 'Authentic TCG deck set.',
    variants: null,
  },
  {
    id: '30th-celebration-tgc-card-set',
    name: '30th CELEBRATION TGC Card Set',
    slug: '30th-celebration-tgc-card-set',
    category: 'pokemon',
    subcategory: 'deck',
    price: 99.99,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/1_813c1ffa-44da-479f-a113-12d22250ad0c.png?v=1783564928',
    badge: null,
    reviews: 0,
    brand: 'TCG SHOP KASUMI',
    description: 'Authentic TCG deck set.',
    variants: null,
  }
];

// =============================================
// PRODUCTS — Grading
// =============================================
export const gradingCards = [
  {
    id: 'psa-grading-service',
    name: 'PSA Grading Service',
    slug: 'psa-grading',
    category: 'grading',
    subcategory: 'psa',
    price: 49.99,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/135146081_c13e1967-25b6-4dad-9a1f-20fa433626d0.jpg?v=1762978542',
    badge: null,
    reviews: 8,
    brand: 'TCG SHOP KASUMI',
    description: 'Submit your cards for professional PSA grading. We handle the entire process from Japan.',
    variants: ['Economy', 'Standard', 'Express'],
  },
];

// =============================================
// CUSTOMER REVIEWS
// =============================================
export const customerReviews = [
  {
    id: 1,
    author: "James K.",
    avatar: "J",
    rating: 5,
    title: "Great serve from beginning to end!",
    text: "Great serve from beginning to end! Will definitely be buying from here again. Excellent packaging and the cards arrived in perfect condition.",
    date: "2026-06-15",
    product: "Abyss Eye Booster Box",
    verified: true,
  },
  {
    id: 2,
    author: "Sarah M.",
    avatar: "S",
    rating: 5,
    title: "Received all 3 boxes way faster than expected!",
    text: "Great seller! Received all 3 of my Pikachu Japan Pokemon center boxes way faster than I thought I was going to get them. Opened them and cards look great! Thank you!",
    date: "2026-06-10",
    product: "Pokemon Center Special Box",
    verified: true,
  },
  {
    id: 3,
    author: "David L.",
    avatar: "D",
    rating: 5,
    title: "Fast shipping and perfect packaging",
    text: "Very efficient shipping, ordered two abyss eye boxes and got my one of my dream chase!!! (Darkrai :D) Both boxes were awesome and loaded with hits (Mega Darkrai EX SAR & Mega Zerarora EX SAR)!!",
    date: "2026-06-05",
    product: "Abyss Eye Booster Box",
    verified: true,
  },
  {
    id: 4,
    author: "Emma R.",
    avatar: "E",
    rating: 5,
    title: "Incredible selection!",
    text: "Found cards that I simply cannot find anywhere else. The communication was fast and professional. My order was perfectly packed with bubble wrap. 10/10!",
    date: "2026-05-28",
    product: "M5 Single Cards",
    verified: true,
  },
  {
    id: 5,
    author: "Carlos V.",
    avatar: "C",
    rating: 5,
    title: "Best Japanese TCG shop online",
    text: "I have ordered multiple times and always have a great experience. The prices are competitive and the cards are always factory sealed as advertised.",
    date: "2026-05-20",
    product: "OP-16 Booster Box",
    verified: true,
  },
  {
    id: 6,
    author: "Yuki T.",
    avatar: "Y",
    rating: 5,
    title: "Authentic Japanese cards, fast delivery",
    text: "Exactly what I ordered, directly from Japan. Customs process was smooth thanks to their duty collection at checkout. Will be a repeat customer!",
    date: "2026-05-15",
    product: "Storm Emeralda Booster Box",
    verified: true,
  },
];

// =============================================
// EU COUNTRIES VAT TABLE
// =============================================
export const euVatRates = [
  { country: "Germany", vat: "19%" },
  { country: "France", vat: "20%" },
  { country: "Spain", vat: "21%" },
  { country: "Netherlands", vat: "21%" },
  { country: "Italy", vat: "22%" },
  { country: "Belgium", vat: "21%" },
  { country: "Sweden", vat: "25%" },
  { country: "Denmark", vat: "25%" },
  { country: "Austria", vat: "20%" },
  { country: "Portugal", vat: "23%" },
  { country: "Czech Republic", vat: "21%" },
  { country: "Greece", vat: "24%" },
  { country: "Luxembourg", vat: "17%" },
  { country: "Hungary*", vat: "27%" },
  { country: "Poland", vat: "23%" },
  { country: "Monaco", vat: "20%" },
];


// =============================================
// PRODUCTS — Graded Cards
// =============================================
export const gradedCards = [
  {
    id: 'psa10-luffy-sr',
    name: '〔PSA10〕Monkey.D.Luffy SR〈ONE PIECE magazine〉',
    slug: 'psa10-luffy-sr',
    category: 'grading',
    subcategory: 'graded',
    price: 365.00,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/135146081_c13e1967-25b6-4dad-9a1f-20fa433626d0.jpg?v=1762978542',
    brand: 'TCG SHOP KASUMI'
  },
  {
    id: 'psa10-luffy-p-one-piece-day25',
    name: '〔PSA10〕Monkey.D.Luffy P〈ONE PIECE DAY25〉',
    slug: 'psa10-luffy-p-one-piece-day25',
    category: 'grading',
    subcategory: 'graded',
    price: 250.00,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/145582380.jpg?v=1769659947',
    brand: 'TCG SHOP KASUMI'
  },
  {
    id: 'psa10-mega-tokyos-pikachu',
    name: '〔PSA10〕Mega Tokyo\'s Pikachu 098/XY-P〈P〉',
    slug: 'psa10-mega-tokyos-pikachu',
    category: 'grading',
    subcategory: 'graded',
    price: 1790.00,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/77662980_72ce98c8-8376-4cfa-a0b5-28b1d9ee3c09.jpg?v=1762977168',
    brand: 'TCG SHOP KASUMI'
  },
  {
    id: 'psa10-ace-luffy-sabo',
    name: '〔PSA10〕ACE/LUFFY/SABO〈SHONEN JUMP #19〉',
    slug: 'psa10-ace-luffy-sabo',
    category: 'grading',
    subcategory: 'graded',
    price: 280.00,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/147816555.jpg?v=1777520200',
    brand: 'TCG SHOP KASUMI'
  },
  {
    id: 'psa10-pikachu-chr',
    name: '〔PSA10〕Pikachu 054/049〈CHR〉',
    slug: 'psa10-pikachu-chr',
    category: 'grading',
    subcategory: 'graded',
    price: 530.00,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/133772237_297fb54e-06f1-42c3-ad1b-f05ab0fe5074.png?v=1776570641',
    brand: 'TCG SHOP KASUMI'
  },
  {
    id: 'psa10-mistys-lapras',
    name: '〔PSA10〕Misty\'s Lapras 072/063〈AR〉',
    slug: 'psa10-mistys-lapras',
    category: 'grading',
    subcategory: 'graded',
    price: 76.50,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/125244926_c7e7f084-0989-40eb-8415-bf9f7f936684.jpg?v=1763201406',
    brand: 'TCG SHOP KASUMI'
  },
  {
    id: 'psa10-solgaleo-lunala-gx',
    name: '〔PSA10〕Solgaleo & Lunala GX (SA) 063/049〈SR〉',
    slug: 'psa10-solgaleo-lunala-gx',
    category: 'grading',
    subcategory: 'graded',
    price: 556.13,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/76454617_c61df9cc-32f5-44da-87ed-b550dbb27452.jpg?v=1763201323',
    brand: 'TCG SHOP KASUMI'
  },
  {
    id: 'psa10-reds-pikachu',
    name: '〔PSA10〕Red\'s Pikachu 270/SM-P〈P〉',
    slug: 'psa10-reds-pikachu',
    category: 'grading',
    subcategory: 'graded',
    price: 1500.00,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/119106835_d60333c9-feba-45fe-9d5a-a71a5f58e399.jpg?v=1762977166',
    brand: 'TCG SHOP KASUMI'
  }
];

// =============================================
// PRODUCTS — Lorcana Boosters
// =============================================
export const lorcanaBoosters = [
  {
    id: 'lorcana-reign-of-jafar',
    name: 'Reign of Jafar TCG BOX',
    slug: 'lorcana-reign-of-jafar',
    category: 'lorcana',
    subcategory: 'booster-box',
    price: 34.25,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/IMG_4154.jpg?v=1771986131',
    brand: 'TCG SHOP KASUMI'
  },
  {
    id: 'lorcana-archazias-island',
    name: 'Archazia\'s Island Booster TCG BOX',
    slug: 'lorcana-archazias-island',
    category: 'lorcana',
    subcategory: 'booster-box',
    price: 34.95,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/61sgiKoOWRL._AC_SL1100_-removebg-preview.png?v=1764121507',
    brand: 'TCG SHOP KASUMI'
  },
  {
    id: 'lorcana-azurite-sea',
    name: 'Azurite Sea Booster TCG BOX',
    slug: 'lorcana-azurite-sea',
    category: 'lorcana',
    subcategory: 'booster-box',
    price: 27.17,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/Photo_25-11-04-11-53-44.652.jpg?v=1762226622',
    brand: 'TCG SHOP KASUMI'
  },
  {
    id: 'lorcana-shimmering-skies',
    name: 'Shimmering Skies Booster TCG BOX',
    slug: 'lorcana-shimmering-skies',
    category: 'lorcana',
    subcategory: 'booster-box',
    price: 18.21,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/61N-SmuS2JL._AC_SL1100_-removebg-preview.png?v=1758106004',
    brand: 'TCG SHOP KASUMI'
  },
  {
    id: 'lorcana-ursulas-return',
    name: 'URSULA\'S RETURN Booster TCG BOX',
    slug: 'lorcana-ursulas-return',
    category: 'lorcana',
    subcategory: 'booster-box',
    price: 22.22,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/Photo_25-07-28-10-17-06.465.jpg?v=1753686589',
    brand: 'TCG SHOP KASUMI'
  },
  {
    id: 'lorcana-into-the-inklands',
    name: 'INTO THE INKLANDS Booster TCG BOX',
    slug: 'lorcana-into-the-inklands',
    category: 'lorcana',
    subcategory: 'booster-box',
    price: 20.80,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/IMG_1307.jpg?v=1747451971',
    brand: 'TCG SHOP KASUMI'
  }
];

// =============================================
// PRODUCTS — OP Decks
// =============================================
export const opDecks = [
  {
    id: 'op-st30-luffy-ace',
    name: '【ST-30】STARTER DECK EX -Luffy & Ace-',
    slug: 'op-st30-luffy-ace',
    category: 'onepiece',
    subcategory: 'deck',
    price: 172.95,
    image: 'https://cdn.shopify.com/s/files/1/0614/1499/8212/files/91LyJj_6BZL._AC_SY879.jpg?v=1776745428',
    brand: 'TCG SHOP KASUMI'
  }
];
