// =============================================
// CURRENCIES
// =============================================
export const currencies = [
  { code: "USD", label: "United States (USD $)", symbol: "$" },
  { code: "AUD", label: "Australia (AUD $)", symbol: "$" },
  { code: "EUR", label: "Austria (EUR €)", symbol: "€" },
  { code: "EUR", label: "Belgium (EUR €)", symbol: "€" },
  { code: "CAD", label: "Canada (CAD $)", symbol: "$" },
  { code: "CNY", label: "China (CNY ¥)", symbol: "¥" },
  { code: "CZK", label: "Czechia (CZK Kč)", symbol: "Kč" },
  { code: "DKK", label: "Denmark (DKK kr.)", symbol: "kr." },
  { code: "EUR", label: "France (EUR €)", symbol: "€" },
  { code: "EUR", label: "Germany (EUR €)", symbol: "€" },
  { code: "EUR", label: "Greece (EUR €)", symbol: "€" },
  { code: "HKD", label: "Hong Kong SAR (HKD $)", symbol: "$" },
  { code: "HUF", label: "Hungary (HUF Ft)", symbol: "Ft" },
  { code: "INR", label: "India (INR ₹)", symbol: "₹" },
  { code: "IDR", label: "Indonesia (IDR Rp)", symbol: "Rp" },
  { code: "ILS", label: "Israel (ILS ₪)", symbol: "₪" },
  { code: "EUR", label: "Italy (EUR €)", symbol: "€" },
  { code: "EUR", label: "Luxembourg (EUR €)", symbol: "€" },
  { code: "MOP", label: "Macao SAR (MOP P)", symbol: "P" },
  { code: "MYR", label: "Malaysia (MYR RM)", symbol: "RM" },
  { code: "MXN", label: "Mexico (MXN $)", symbol: "$" },
  { code: "EUR", label: "Monaco (EUR €)", symbol: "€" },
  { code: "EUR", label: "Montenegro (EUR €)", symbol: "€" },
  { code: "NPR", label: "Nepal (NPR Rs.)", symbol: "Rs." },
  { code: "EUR", label: "Netherlands (EUR €)", symbol: "€" },
  { code: "NZD", label: "New Zealand (NZD $)", symbol: "$" },
  { code: "NOK", label: "Norway (NOK kr)", symbol: "kr" },
  { code: "PHP", label: "Philippines (PHP ₱)", symbol: "₱" },
  { code: "PLN", label: "Poland (PLN zł)", symbol: "zł" },
  { code: "EUR", label: "Portugal (EUR €)", symbol: "€" },
  { code: "QAR", label: "Qatar (QAR ر.ق)", symbol: "ر.ق" },
  { code: "SGD", label: "Singapore (SGD $)", symbol: "$" },
  { code: "KRW", label: "South Korea (KRW ₩)", symbol: "₩" },
  { code: "EUR", label: "Spain (EUR €)", symbol: "€" },
  { code: "SEK", label: "Sweden (SEK kr)", symbol: "kr" },
  { code: "CHF", label: "Switzerland (CHF CHF)", symbol: "CHF" },
  { code: "TWD", label: "Taiwan (TWD $)", symbol: "$" },
  { code: "THB", label: "Thailand (THB ฿)", symbol: "฿" },
  { code: "AED", label: "United Arab Emirates (AED د.إ)", symbol: "د.إ" },
  { code: "GBP", label: "United Kingdom (GBP £)", symbol: "£" },
  { code: "VND", label: "Vietnam (VND ₫)", symbol: "₫" },
];

// =============================================
// CATEGORIES
// =============================================
export const categories = [
  { id: "pokemon", name: "Pokémon Cards", slug: "pokemon", emoji: "⚡" },
  { id: "onepiece", name: "One Piece Cards", slug: "one-piece", emoji: "⚓" },
  { id: "lorcana", name: "Disney LORCANA", slug: "disney-lorcana", emoji: "✨" },
  { id: "dragonball", name: "Dragon Ball Cards", slug: "dragon-ball", emoji: "🐉" },
  { id: "grading", name: "Grading Cards", slug: "grading", emoji: "🏆" },
];

// =============================================
// PRODUCTS — Pokémon Booster Boxes
// =============================================
export const pokemonBoosterBoxes = [
  {
    id: "tcg0567",
    name: "【M6】Storm Emeralda TCG BOX & CASE〔Factory Sealed〕",
    slug: "m6-storm-emeralda-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 89.99,
    image: "https://omotenashitcg.com/cdn/shop/files/715FaccxhwL._AC_SL1500_600x600_crop_center.jpg",
    badge: "new",
    reviews: 0,
    brand: "Pokémon",
    description: "The latest Mega TCG set, Storm Emeralda, featuring powerful new cards and stunning artwork. Factory sealed for guaranteed authenticity.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
  {
    id: "tcg0566",
    name: "【M6a】30th CELEBRATION TCG BOX & CASE〔Factory Sealed〕",
    slug: "m6a-30th-celebration-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 119.99,
    image: "https://omotenashitcg.com/cdn/shop/files/715FaccxhwL._AC_SL1500_600x600_crop_center.jpg",
    badge: "hot",
    reviews: 0,
    brand: "Pokémon",
    description: "Celebrate 30 years of Pokémon with this special anniversary set. Includes exclusive celebration cards.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
  {
    id: "tcg0561",
    name: "【M5】Abyss Eye Booster TCG BOX & CASE〔Factory Sealed〕",
    slug: "m5-abyss-eye-booster-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 79.99,
    image: "https://omotenashitcg.com/cdn/shop/files/715FaccxhwL._AC_SL1500_600x600_crop_center.jpg",
    badge: null,
    reviews: 13,
    brand: "Pokémon",
    description: "Dive into the depths with the Abyss Eye set. Features Darkrai EX and other powerful deep-sea Pokémon.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
  {
    id: "tcg0557",
    name: "【M4】Ninja Spinner Booster TCG BOX & CASE〔Factory Sealed〕",
    slug: "m4-ninja-spinner-booster-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 74.99,
    image: "https://omotenashitcg.com/cdn/shop/files/PRB-02_ONE_PIECE_CARD_THE_BEST_Vol.2.png",
    badge: null,
    reviews: 5,
    brand: "Pokémon",
    description: "Fast and fierce ninja-themed set with powerful Fighting and Dark type cards.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
  {
    id: "tcg0554",
    name: "【M3】Munikis Zero Booster TCG BOX & CASE〔Factory Sealed〕",
    slug: "m3-munikis-zero-booster-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 69.99,
    image: "https://omotenashitcg.com/cdn/shop/files/PRB-02_ONE_PIECE_CARD_THE_BEST_Vol.2.png",
    badge: null,
    reviews: 3,
    brand: "Pokémon",
    description: "Munikis Zero brings a new level of strategy to the Mega TCG with innovative card mechanics.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
  {
    id: "tcg0548",
    name: "【M2a】MEGA Dream ex Booster TCG BOX & CASE〔Factory Sealed〕",
    slug: "m2a-mega-dream-ex-booster-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 64.99,
    image: "https://omotenashitcg.com/cdn/shop/files/PRB-02_ONE_PIECE_CARD_THE_BEST_Vol.2.png",
    badge: null,
    reviews: 15,
    brand: "Pokémon",
    description: "MEGA Dream ex features the most beloved Pokémon in their Mega Evolution forms.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
  {
    id: "tcg0265",
    name: "【SV11W】White Flare Booster TCG BOX & CASE〔Factory Sealed〕",
    slug: "sv11w-white-flare-booster-tcg-box-case",
    category: "pokemon",
    subcategory: "booster-box",
    price: 84.99,
    image: "https://omotenashitcg.com/cdn/shop/files/5_89fad6ab-c531-4f9a-99ae-c6ed9cf29f68_600x600_crop_center.png",
    badge: null,
    reviews: 2,
    brand: "Pokémon",
    description: "Scarlet & Violet set featuring powerful Paradox Pokémon and ancient forms.",
    variants: ["1 BOX", "1 CASE (6 BOX)"],
  },
];

// =============================================
// PRODUCTS — One Piece Booster Boxes
// =============================================
export const onePieceBoosterBoxes = [
  {
    id: "tcg0568",
    name: "【OP-17】The World's Strongest Warriors TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-17-worlds-strongest-warriors-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 94.99,
    image: "https://omotenashitcg.com/cdn/shop/files/5_89fad6ab-c531-4f9a-99ae-c6ed9cf29f68_600x600_crop_center.png",
    badge: "new",
    reviews: 0,
    brand: "One Piece",
    description: "The latest One Piece TCG set featuring the World's Strongest Warriors with powerful new cards.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg0560",
    name: "【OP-16】The Time Of Battle TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-16-time-of-battle-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 84.99,
    image: "https://omotenashitcg.com/cdn/shop/files/5_89fad6ab-c531-4f9a-99ae-c6ed9cf29f68_600x600_crop_center.png",
    badge: "hot",
    reviews: 5,
    brand: "One Piece",
    description: "The Time of Battle features epic clashes and iconic moments from the One Piece anime.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg0555",
    name: "【OP-15】Adventure on the Island of the Gods TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-15-adventure-island-gods-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 79.99,
    image: "https://omotenashitcg.com/cdn/shop/files/5_89fad6ab-c531-4f9a-99ae-c6ed9cf29f68_600x600_crop_center.png",
    badge: null,
    reviews: 3,
    brand: "One Piece",
    description: "Adventure on the Island of the Gods brings the Egghead arc to life with stunning cards.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
  {
    id: "tcg0547",
    name: "【OP-14】The Azure Sea's Seven Booster TCG BOX & CASE〔Factory Sealed〕",
    slug: "op-14-azure-seas-seven-tcg-box-case",
    category: "onepiece",
    subcategory: "booster-box",
    price: 74.99,
    image: "https://omotenashitcg.com/cdn/shop/files/5_89fad6ab-c531-4f9a-99ae-c6ed9cf29f68_600x600_crop_center.png",
    badge: null,
    reviews: 4,
    brand: "One Piece",
    description: "Features the Shichibukai - Seven Warlords of the Sea with powerful leader cards.",
    variants: ["1 BOX", "1 CASE (12 BOX)"],
  },
];

// =============================================
// PRODUCTS — Singles
// =============================================
export const singleCards = [
  {
    id: "mega-chandelure-ex-036-081",
    name: "[M5] Mega Chandelure ex 036/081〈RR〉",
    slug: "mega-chandelure-ex-036-081",
    category: "pokemon",
    subcategory: "single",
    price: 12.99,
    image: "https://omotenashitcg.com/cdn/shop/files/5_89fad6ab-c531-4f9a-99ae-c6ed9cf29f68_600x600_crop_center.png",
    badge: null,
    reviews: 0,
    brand: "Pokémon",
    variants: ["Near Mint (NM)", "Excellent (EX)", "Very Good (VG)"],
  },
  {
    id: "brave-bangle-107-081",
    name: "[M5] Brave Bangle 107/081〈SR〉",
    slug: "brave-bangle-107-081",
    category: "pokemon",
    subcategory: "single",
    price: 8.99,
    image: "https://omotenashitcg.com/cdn/shop/files/xmF1v39ZqNhWwG78VOKaL62V8o4oBARG8EZOK4C2_500x_9d3b8e93-806a-41e6-bbda-c3d990cd7029_600x600_crop_center.jpg",
    badge: null,
    reviews: 0,
    brand: "Pokémon",
    variants: ["Near Mint (NM)", "Excellent (EX)", "Very Good (VG)"],
  },
  {
    id: "crushing-hammer-104-081",
    name: "[M5] Crushing Hammer 104/081〈SR〉",
    slug: "crushing-hammer-104-081",
    category: "pokemon",
    subcategory: "single",
    price: 7.50,
    image: "https://omotenashitcg.com/cdn/shop/files/xmF1v39ZqNhWwG78VOKaL62V8o4oBARG8EZOK4C2_500x_9d3b8e93-806a-41e6-bbda-c3d990cd7029_600x600_crop_center.jpg",
    badge: null,
    reviews: 0,
    brand: "Pokémon",
    variants: ["Near Mint (NM)", "Excellent (EX)", "Very Good (VG)"],
  },
  {
    id: "zarude-090-081",
    name: "[M5] Zarude 090/081〈AR〉",
    slug: "zarude-090-081",
    category: "pokemon",
    subcategory: "single",
    price: 6.99,
    image: "https://omotenashitcg.com/cdn/shop/files/S__68248428_c19e5c48-24f0-43c1-9420-b51b21f58441.jpg",
    badge: null,
    reviews: 0,
    brand: "Pokémon",
    variants: ["Near Mint (NM)", "Excellent (EX)", "Very Good (VG)"],
  },
  {
    id: "monkey-d-luffy-natsucomi-2026",
    name: "Monkey.D.Luffy Watermelon〈NatsuComi Summer Comics Fair 2026〉",
    slug: "monkey-d-luffy-natsucomi-summer-comics-fair-2026",
    category: "onepiece",
    subcategory: "single",
    price: 24.99,
    image: "https://omotenashitcg.com/cdn/shop/files/S__68248428_c19e5c48-24f0-43c1-9420-b51b21f58441.jpg",
    badge: "hot",
    reviews: 0,
    brand: "One Piece",
    variants: ["Near Mint (NM)", "Excellent (EX)"],
  },
];

// =============================================
// PRODUCTS — Deck Sets
// =============================================
export const deckSets = [
  {
    id: "30th-celebration-futuristic-box",
    name: "30th CELEBRATION FUTURISTIC BOX",
    slug: "30th-celebration-futuristic-box",
    category: "pokemon",
    subcategory: "deck",
    price: 149.99,
    image: "https://omotenashitcg.com/cdn/shop/files/S__68248428_c19e5c48-24f0-43c1-9420-b51b21f58441.jpg",
    badge: "new",
    reviews: 0,
    brand: "Pokémon",
    description: "A special commemorative box celebrating 30 years of Pokémon with exclusive futuristic design.",
    variants: null,
  },
  {
    id: "tcg0570",
    name: "30th CELEBRATION Premium TCG Deck set Espeon・Umbreon",
    slug: "30th-celebration-premium-deck-espeon-umbreon",
    category: "pokemon",
    subcategory: "deck",
    price: 129.99,
    image: "https://omotenashitcg.com/cdn/shop/files/51XbrLjTUtL._AC_SL1500_600x600_crop_center.jpg",
    badge: "new",
    reviews: 0,
    brand: "Pokémon",
    description: "Premium deck set featuring the iconic Espeon and Umbreon, perfect for collectors.",
    variants: null,
  },
  {
    id: "tcg0400",
    name: "【SV10】The Glory of Team Rocket TCG Attache Case",
    slug: "sv10-glory-of-team-rocket-attache-case",
    category: "pokemon",
    subcategory: "deck",
    price: 189.99,
    image: "https://omotenashitcg.com/cdn/shop/files/51XbrLjTUtL._AC_SL1500_600x600_crop_center.jpg",
    badge: "sale",
    reviews: 22,
    brand: "Pokémon",
    description: "A premium attache case themed around the iconic Team Rocket, containing exclusive cards.",
    variants: null,
  },
  {
    id: "tcg0032",
    name: "Pokémon Card Game CLASSIC Deck TCG Set",
    slug: "pokemon-card-game-classic-deck-tcg-set",
    category: "pokemon",
    subcategory: "deck",
    price: 299.99,
    image: "https://omotenashitcg.com/cdn/shop/files/51XbrLjTUtL._AC_SL1500_600x600_crop_center.jpg",
    badge: null,
    reviews: 2,
    brand: "Pokémon",
    description: "Relive the original Pokémon TCG experience with this classic deck set.",
    variants: null,
  },
];

// =============================================
// PRODUCTS — Grading
// =============================================
export const gradingCards = [
  {
    id: "psa-grading-service",
    name: "PSA Grading Service",
    slug: "psa-grading",
    category: "grading",
    subcategory: "psa",
    price: 49.99,
    image: "https://omotenashitcg.com/cdn/shop/files/51XbrLjTUtL._AC_SL1500_600x600_crop_center.jpg",
    badge: null,
    reviews: 8,
    brand: "PSA",
    description: "Submit your cards for professional PSA grading. We handle the entire process from Japan.",
    variants: ["Economy", "Standard", "Express"],
  },
];

// =============================================
// CUSTOMER REVIEWS
// =============================================
export const customerReviews = [
  {
    id: 1,
    author: "James K.",
    avatar: "J",
    rating: 5,
    title: "Great serve from beginning to end!",
    text: "Great serve from beginning to end! Will definitely be buying from here again. Excellent packaging and the cards arrived in perfect condition.",
    date: "2026-06-15",
    product: "Abyss Eye Booster Box",
    verified: true,
  },
  {
    id: 2,
    author: "Sarah M.",
    avatar: "S",
    rating: 5,
    title: "Received all 3 boxes way faster than expected!",
    text: "Great seller! Received all 3 of my Pikachu Japan Pokemon center boxes way faster than I thought I was going to get them. Opened them and cards look great! Thank you!",
    date: "2026-06-10",
    product: "Pokemon Center Special Box",
    verified: true,
  },
  {
    id: 3,
    author: "David L.",
    avatar: "D",
    rating: 5,
    title: "Fast shipping and perfect packaging",
    text: "Very efficient shipping, ordered two abyss eye boxes and got my one of my dream chase!!! (Darkrai :D) Both boxes were awesome and loaded with hits (Mega Darkrai EX SAR & Mega Zerarora EX SAR)!!",
    date: "2026-06-05",
    product: "Abyss Eye Booster Box",
    verified: true,
  },
  {
    id: 4,
    author: "Emma R.",
    avatar: "E",
    rating: 5,
    title: "Incredible selection!",
    text: "Found cards that I simply cannot find anywhere else. The communication was fast and professional. My order was perfectly packed with bubble wrap. 10/10!",
    date: "2026-05-28",
    product: "M5 Single Cards",
    verified: true,
  },
  {
    id: 5,
    author: "Carlos V.",
    avatar: "C",
    rating: 5,
    title: "Best Japanese TCG shop online",
    text: "I have ordered multiple times and always have a great experience. The prices are competitive and the cards are always factory sealed as advertised.",
    date: "2026-05-20",
    product: "OP-16 Booster Box",
    verified: true,
  },
  {
    id: 6,
    author: "Yuki T.",
    avatar: "Y",
    rating: 5,
    title: "Authentic Japanese cards, fast delivery",
    text: "Exactly what I ordered, directly from Japan. Customs process was smooth thanks to their duty collection at checkout. Will be a repeat customer!",
    date: "2026-05-15",
    product: "White Flare Booster Box",
    verified: true,
  },
];

// =============================================
// EU COUNTRIES VAT TABLE
// =============================================
export const euVatRates = [
  { country: "Germany", vat: "19%" },
  { country: "France", vat: "20%" },
  { country: "Spain", vat: "21%" },
  { country: "Netherlands", vat: "21%" },
  { country: "Italy", vat: "22%" },
  { country: "Belgium", vat: "21%" },
  { country: "Sweden", vat: "25%" },
  { country: "Denmark", vat: "25%" },
  { country: "Austria", vat: "20%" },
  { country: "Portugal", vat: "23%" },
  { country: "Czech Republic", vat: "21%" },
  { country: "Greece", vat: "24%" },
  { country: "Luxembourg", vat: "17%" },
  { country: "Hungary*", vat: "27%" },
  { country: "Poland", vat: "23%" },
  { country: "Monaco", vat: "20%" },
];
