const fs = require('fs');

const reviews = [
  {
    id: 1,
    author: "James K.",
    avatar: "J",
    rating: 5,
    title: "Great serve from beginning to end!",
    text: "Great serve from beginning to end! Will definitely be buying from here again. Excellent packaging and the cards arrived in perfect condition.",
    date: "2026-06-15",
    product: "Abyss Eye Booster Box",
    verified: true,
  },
  {
    id: 2,
    author: "Sarah M.",
    avatar: "S",
    rating: 5,
    title: "Received all 3 boxes way faster than expected!",
    text: "Great seller! Received all 3 of my Pikachu Japan Pokemon center boxes way faster than I thought I was going to get them. Opened them and cards look great! Thank you!",
    date: "2026-06-10",
    product: "Pokemon Center Special Box",
    verified: true,
  },
  {
    id: 3,
    author: "David L.",
    avatar: "D",
    rating: 5,
    title: "Fast shipping and perfect packaging",
    text: "Very efficient shipping, ordered two abyss eye boxes and got my one of my dream chase!!! (Darkrai :D) Both boxes were awesome and loaded with hits (Mega Darkrai EX SAR & Mega Zerarora EX SAR)!!",
    date: "2026-06-05",
    product: "Abyss Eye Booster Box",
    verified: true,
  },
  {
    id: 4,
    author: "Emma R.",
    avatar: "E",
    rating: 5,
    title: "Incredible selection!",
    text: "Found cards that I simply cannot find anywhere else. The communication was fast and professional. My order was perfectly packed with bubble wrap. 10/10!",
    date: "2026-05-28",
    product: "M5 Single Cards",
    verified: true,
  },
  {
    id: 5,
    author: "Carlos V.",
    avatar: "C",
    rating: 5,
    title: "Best Japanese TCG shop online",
    text: "I have ordered multiple times and always have a great experience. The prices are competitive and the cards are always factory sealed as advertised.",
    date: "2026-05-20",
    product: "OP-16 Booster Box",
    verified: true,
  },
  {
    id: 6,
    author: "Yuki T.",
    avatar: "Y",
    rating: 5,
    title: "Authentic Japanese cards, fast delivery",
    text: "Exactly what I ordered, directly from Japan. Customs process was smooth thanks to their duty collection at checkout. Will be a repeat customer!",
    date: "2026-05-15",
    product: "Storm Emeralda Booster Box",
    verified: true,
  },
  {
    id: 7,
    author: "Michael B.",
    avatar: "M",
    rating: 5,
    title: "Pulled my chase card!",
    text: "Fast delivery, original packaging, and pulled the Alt Art Luffy! Couldn't be happier with this purchase. Packaged very safely.",
    date: "2026-06-18",
    product: "Romance Dawn Booster Box (OP-01)",
    verified: true,
  },
  {
    id: 8,
    author: "Sophie L.",
    avatar: "S",
    rating: 5,
    title: "Very well packaged",
    text: "Bought 2 Surging Sparks ETBs. The shipping was surprisingly quick to France, and the packaging was super heavy duty. Zero damage to the corners.",
    date: "2026-06-22",
    product: "Surging Sparks ETB",
    verified: true,
  },
  {
    id: 9,
    author: "Alexandre P.",
    avatar: "A",
    rating: 5,
    title: "Exceptional service",
    text: "I was hesitant to order from overseas but KAGAMI made it so easy. All taxes were handled at checkout. The grading cards arrived in perfect condition.",
    date: "2026-06-25",
    product: "Graded Cards",
    verified: true,
  },
  {
    id: 10,
    author: "Oliver H.",
    avatar: "O",
    rating: 5,
    title: "100% Genuine, Sealed!",
    text: "Checked the shrink wrap upon arrival and it is 100% authentic factory seal. Pulled amazing cards from the Dragon Ball box. Will definitely purchase again.",
    date: "2026-06-29",
    product: "Awakened Pulse Booster Box (FB01)",
    verified: true,
  },
  {
    id: 11,
    author: "Elena G.",
    avatar: "E",
    rating: 5,
    title: "Fast international shipping",
    text: "Order arrived in Germany in just 5 days! Very well packed with bubble wrap. Perfect condition booster bundles.",
    date: "2026-07-02",
    product: "Booster Bundles",
    verified: true,
  },
  {
    id: 12,
    author: "Ryosuke K.",
    avatar: "R",
    rating: 5,
    title: "Excellent shop!",
    text: "One of the best places to buy authentic Japanese TCG. Highly recommend for any serious collector.",
    date: "2026-07-05",
    product: "Shiny Treasure Booster Box (SV4a)",
    verified: true,
  },
  {
    id: 13,
    author: "Chloe W.",
    avatar: "C",
    rating: 5,
    title: "Highly recommended store",
    text: "Customer service is top-notch. They answered my questions about shipping times within minutes. The ETBs were packed with extreme care.",
    date: "2026-07-08",
    product: "Prismatic Evolutions ETB",
    verified: true,
  },
  {
    id: 14,
    author: "Lucas D.",
    avatar: "L",
    rating: 5,
    title: "Perfect deal and authentic product",
    text: "Authentic Yu-Gi-Oh retro pack. Got exactly what was described. Delivery was quick and tracking was accurate.",
    date: "2026-07-10",
    product: "Retro Pack Booster Box",
    verified: true,
  },
  {
    id: 15,
    author: "Isabella N.",
    avatar: "I",
    rating: 5,
    title: "Amazing pulls and fast delivery",
    text: "Got the box in under a week. Everything was wrapped beautifully. Pulled the special illustration rare Vivi!",
    date: "2026-07-12",
    product: "OP-12 Booster Box",
    verified: true,
  },
  {
    id: 16,
    author: "Tyler F.",
    avatar: "T",
    rating: 5,
    title: "A+ Seller",
    text: "Super happy with the purchase. The condition of the boxes was pristine. Will buy my next case from here.",
    date: "2026-07-14",
    product: "Two Legends Booster Box (OP-08)",
    verified: true,
  },
  {
    id: 17,
    author: "Mia S.",
    avatar: "M",
    rating: 5,
    title: "Great packaging",
    text: "No crushed corners, bubble wrapped perfectly. Thank you for the great service!",
    date: "2026-07-15",
    product: "Stellar Crown ETB",
    verified: true,
  },
  {
    id: 18,
    author: "Filippo M.",
    avatar: "F",
    rating: 5,
    title: "Ottimo venditore!",
    text: "Spedizione velocissima per l'Italia e imballaggio perfetto. Prodotti originali sigillati.",
    date: "2026-07-17",
    product: "Rarity Collection V",
    verified: true,
  },
  {
    id: 19,
    author: "Benjamin T.",
    avatar: "B",
    rating: 5,
    title: "Excellent service and selection",
    text: "I bought the PSA 10 Pikachu and it arrived in a thick protective sleeve, heavily bubble-wrapped. Fantastic transaction.",
    date: "2026-07-19",
    product: "Graded Cards",
    verified: true,
  },
  {
    id: 20,
    author: "Amelie R.",
    avatar: "A",
    rating: 5,
    title: "Très satisfait",
    text: "Livraison rapide, colis très bien protégé. Les cartes sont magnifiques. Je recommande ce site sans hésiter.",
    date: "2026-07-21",
    product: "Black Bolt Booster Box (SV11B)",
    verified: true,
  },
  {
    id: 21,
    author: "Daniel K.",
    avatar: "D",
    rating: 5,
    title: "Awesome pulls from DB",
    text: "My box of Raging Roar arrived in perfect shape. Pulled the secret rare Son Goku! Very happy.",
    date: "2026-07-22",
    product: "Raging Roar Booster Box (FB03)",
    verified: true,
  },
  {
    id: 22,
    author: "Sophia A.",
    avatar: "S",
    rating: 5,
    title: "Best place for Japanese boxes",
    text: "Fast shipping, fair prices, and clean shrink wrap. Highly recommended place for TCG enthusiasts.",
    date: "2026-07-24",
    product: "Evolving Skies ETB",
    verified: true,
  },
  {
    id: 23,
    author: "Nathan J.",
    avatar: "N",
    rating: 5,
    title: "Will buy again!",
    text: "Amazing communication and prompt dispatch. The boxes look beautiful in my display cabinet.",
    date: "2026-07-25",
    product: "30th Celebration ETB",
    verified: true,
  },
  {
    id: 24,
    author: "Zoe D.",
    avatar: "Z",
    rating: 5,
    title: "Perfect purchase",
    text: "Everything was smooth. Item was shipped within 24 hours of purchase. Very well wrapped.",
    date: "2026-07-26",
    product: "OP-05 Booster Box",
    verified: true,
  },
  {
    id: 25,
    author: "Matthew L.",
    avatar: "M",
    rating: 5,
    title: "Excellent packaging",
    text: "Boxes are in perfect shape. Fast delivery to Australia. Couldn't ask for a better service.",
    date: "2026-07-28",
    product: "One Piece Decks & Sets",
    verified: true,
  },
  {
    id: 26,
    author: "Charlotte H.",
    avatar: "C",
    rating: 5,
    title: "Authentic and fast",
    text: "Got my PSA graded card and the case is scratch-free. Shipping was fast and tracked all the way.",
    date: "2026-07-29",
    product: "Graded Cards",
    verified: true,
  },
  {
    id: 27,
    author: "Ethan R.",
    avatar: "E",
    rating: 5,
    title: "Great pricing and speed",
    text: "Cheaper than local card shops and shipping was faster than expected. 10/10 shop.",
    date: "2026-07-30",
    product: "Temporal Forces ETB",
    verified: true,
  },
  {
    id: 28,
    author: "Emily B.",
    avatar: "E",
    rating: 5,
    title: "Lovely experience",
    text: "Highly recommend KAGAMI. Very professional, fast shipping, and extremely secure packing.",
    date: "2026-08-01",
    product: "30th Celebration Booster Bundle",
    verified: true,
  },
  {
    id: 29,
    author: "Leo M.",
    avatar: "L",
    rating: 5,
    title: "Top-notch TCG supplier",
    text: "Authentic Japanese product, secure packaging, fast dispatch. Best place to order.",
    date: "2026-08-03",
    product: "OP-09 Booster Box",
    verified: true,
  },
  {
    id: 30,
    author: "Freya S.",
    avatar: "F",
    rating: 5,
    title: "Incredible shop!",
    text: "Order arrived safely in the UK. Fantastic packaging, genuine product, highly recommend KAGAMI.",
    date: "2026-08-04",
    product: "Prismatic Evolutions Booster Bundle",
    verified: true,
  },
  {
    id: 31,
    author: "Hugo V.",
    avatar: "H",
    rating: 5,
    title: "Perfect sealed box",
    text: "Awesome experience. Fast shipping and the box is completely pristine. Highly recommend.",
    date: "2026-08-05",
    product: "Rivals Clash Booster Box (FB06)",
    verified: true,
  },
  {
    id: 32,
    author: "Aria C.",
    avatar: "A",
    rating: 5,
    title: "Exceptional quality",
    text: "Perfect customer support, quick shipping, and genuine card sets. Extremely happy collector!",
    date: "2026-08-06",
    product: "White Flare ETB",
    verified: true,
  }
];

// Read src/lib/data.js
let data = fs.readFileSync('src/lib/data.js', 'utf8');

// Find start and end of customerReviews
const startMarker = 'export const customerReviews = [';
const startIndex = data.indexOf(startMarker);
if (startIndex === -1) {
  console.error('Could not find customerReviews array!');
  process.exit(1);
}

// Find the closing bracket of the array
let endIndex = -1;
let openBrackets = 0;
for (let i = startIndex + startMarker.length - 1; i < data.length; i++) {
  if (data[i] === '[') openBrackets++;
  if (data[i] === ']') {
    openBrackets--;
    if (openBrackets === 0) {
      endIndex = i;
      break;
    }
  }
}

if (endIndex === -1) {
  console.error('Could not find end of customerReviews array!');
  process.exit(1);
}

// Construct the new array content block
const newReviewsStr = '\n' + reviews.map(r => `  {
    id: ${r.id},
    author: "${r.author}",
    avatar: "${r.avatar}",
    rating: ${r.rating},
    title: "${r.title}",
    text: "${r.text}",
    date: "${r.date}",
    product: "${r.product}",
    verified: ${r.verified},
  }`).join(',\n') + '\n';

// Replace the block
data = data.substring(0, startIndex + startMarker.length) + newReviewsStr + data.substring(endIndex);

fs.writeFileSync('src/lib/data.js', data);
console.log('Successfully expanded customerReviews list in data.js to 32 reviews!');
